### ISSUE TITLE
mdast-react

### ISSUE THREAD

**Issue by tmcw** [browniefed/babel-plugin-markdown-react#1]
Just to put this on your radar: https://github.com/mapbox/mdast-react generates an actual React DOM from Markdown source by using [mdast](https://github.com/wooorm/mdast) to generate and AST and then createElement calls all the way down. This way we can avoid using dangerously\* methods and can even ban them on the application level.

**Comment by browniefed** [comment]
@tmcw I was looking for something like that, but was looking at markdown=>ast=>transform to babel acorn ast.
The main meaning behind my stuff is a blog platform in React, but whitespace gets stripped in processing JSX, so hoping this was a way to pre-process markdown to react as an ast.

**Comment by browniefed** [comment]
Looking at integrating it now, thanks for the heads up.

**Comment by browniefed** [comment]
@tmcw actually decided not to use mdast, ended up just compiling to HTML then bringing in the babel parser to get the babel AST and replacing the node children with the AST. Seems to work?

```
if (this.isJSXElement(node) && node.openingElement.name.name === 'Markdown' && node.children.length === 1) {
            var md = new Remarkable("full");
            var strings = node.children[0].raw.split(NEW_LINE);
            var spacing = detectSpacing(strings);
            var content = _(strings).map((str) => _.drop(str, spacing).join('')).value().join(NEW_LINE);

            var markdownAST = babel.parse('<div>' + NEW_LINE + md.render(content) + NEW_LINE + '</div>');

            node.children = [markdownAST.body[0].expression]
        }
```
