### ISSUE TITLE
Uncaught Error: Invariant Violation: onlyChild must be passed a children with exactly one child.

### ISSUE THREAD

**Issue by alansouzati** [browniefed/babel-plugin-markdown-react#4]
I started to get this weird issue when trying to use Markdown component

This is how I use it, any idea why it is complaining about the onlyChild ?

``````
  <Markdown>
     # Hello!

     ```
       # H1

       ## H2
     ```
  </Markdown>
``````

The weird thing is that the same code worked yesterday :(

**Comment by browniefed** [comment]
What my plugin does is wraps everything in a `<div>MarkdownHtml</div>` and the Markdown will throw that error in the event that things didn't get processed correctly.
I'll look into it though, make sure your stuff is actually outputting correctly though.
You can always run `babel --plugins babel-plugin-markdown-react someFileWithMarkdown.js -o processedFile.js`

aka: It's a safe guard to warn when things break.

**Comment by browniefed** [comment]
Just tried your example it works for me... of course it does.

**Comment by browniefed** [comment]
![http://i.imgur.com/h4n85h6.png](http://i.imgur.com/h4n85h6.png)

**Comment by alansouzati** [comment]
Thanks for trying. I will figure it out ;)

**Comment by browniefed** [comment]
@alansouzati no worries let me know if you can't figure it out. Also I may be switching away from remarkable to another markdown processor, one that gives me a little more control over the rendering, but it shouldn't effect you.

**Comment by alansouzati** [comment]
Yeah, i got it. Somehow the plugin configuration disappeared from my loader config. I'm able to test the stuff again, works great thank you.

You asked about feedback, and here is one. Having to load the Markdown component inside my React component sounds strange. A suggestion might be to use a pre code tag with a specific class name, for example:

``````
  <pre><code className="lang-markdown">
     # Hello!

     ```
       # H1

       ## H2
     ```
  </code></pre>
``````

So you can then process these components from you babel plugin. 

Regarding using another markdown processor, have you considered `marked`? I'm using `markdown-loader` which uses marked behind the scenes. They automagically add the lang classes as I described above.

Great stuff man. Let's keep in touch.

**Comment by browniefed** [comment]
Yep, I was planning on changing to marked since it allows me to hook into render process. Might be able to avoid rendering to HTML then parsing AST, may be able to render directly to a babel AST, not likely but worth investigating.

The markdown component is just so I have something specific to look for. The `<pre><code>` option would be for mostly rendering stuff where whitespace matters, in my case it doesn't, and also not everything I'm writing is a code example, mostly writing blogs with code examples.

I'm investigating replacing `<Markdown>` with the div rather than replacing the children, that way you don't need to actually include a Markdown component. Since  I don't like adding additional markup, however in this case I have to add an extra div.

**Comment by alansouzati** [comment]
And extra div sounds better to me ;)

On Tue, Aug 25, 2015 at 1:28 PM, Jason Brown notifications@github.com
wrote:

> Yep, I was planning on changing to marked since it allows me to hook into
> render process. Might be able to avoid rendering to HTML then parsing AST,
> may be able to render directly to a babel AST, not likely but worth
> investigating.
> 
> The markdown component is just so I have something specific to look for.
> The <pre><code> option would be for mostly rendering stuff where
> whitespace matters, in my case it doesn't, and also not everything I'm
> writing is a code example, mostly writing blogs with code examples.
> 
> I'm investigating replacing <Markdown> with the div rather than replacing
> the children, that way you don't need to actually include a Markdown
> component. Since I don't like adding additional markup, however in this
> case I have to add an extra div.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/browniefed/babel-plugin-markdown-react/issues/4#issuecomment-134730743
> .

## 

## 

Alan Souza
Software Engineer
Contact: +1 (408) 421 - 6341

**Comment by browniefed** [comment]
@alansouzati converted to marked, should add proper `className="hljs"` on code blocks so you should be able to do 

```
var style = require('highlight.js/styles/default.css');
var darkula = require('highlight.js/styles/darkula.css'); // or other theme
```

Or include the CSS another way, and things should auto-highlight without initializing the JS.
